// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users/search": {
            "get": {
                "description": "Busca usuarios cuyo nombre coincida parcialmente con el query enviado.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Buscar usuarios",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Texto de búsqueda parcial",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    },
                    "400": {
                        "description": "Parámetro 'q' faltante",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error al buscar en la base de datos",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vaults/{id}/invite": {
            "post": {
                "description": "Permite invitar a un usuario existente a un vault como colaborador",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vaults"
                ],
                "summary": "Invitar a un usuario a un vault",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Vault",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nombre de usuario",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.InviteUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vaults/{id}/role": {
            "patch": {
                "description": "Permite cambiar el rol de un colaborador existente en un vault (por ejemplo, de viewer a collaborator).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vaults"
                ],
                "summary": "Actualizar el rol de un usuario en un vault",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Vault",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos para actualizar el rol",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateVaultRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.InviteUserRequest": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string",
                    "example": "juanito123"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Ocurrio un error inesperado en el servidor"
                }
            }
        },
        "dto.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Rol actualizado exitosamente"
                }
            }
        },
        "dto.UpdateVaultRoleRequest": {
            "type": "object",
            "properties": {
                "new_role": {
                    "type": "string",
                    "example": "viewer"
                },
                "username": {
                    "type": "string",
                    "example": "juanito123"
                }
            }
        },
        "models.Note": {
            "type": "object",
            "properties": {
                "attachments": {
                    "description": "Relación: archivos adjuntos",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NoteAttachment"
                    }
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "notePermissions": {
                    "description": "Relación: permisos de nota",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NotePermission"
                    }
                },
                "noteTags": {
                    "description": "Relación: etiquetado",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NoteTag"
                    }
                },
                "owner": {
                    "$ref": "#/definitions/models.User"
                },
                "ownerID": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "vault": {
                    "$ref": "#/definitions/models.Vault"
                },
                "vaultID": {
                    "type": "string"
                }
            }
        },
        "models.NoteAttachment": {
            "type": "object",
            "properties": {
                "fileURL": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lineNumber": {
                    "type": "integer"
                },
                "note": {
                    "$ref": "#/definitions/models.Note"
                },
                "noteID": {
                    "type": "string"
                },
                "uploadedAt": {
                    "type": "string"
                }
            }
        },
        "models.NotePermission": {
            "type": "object",
            "properties": {
                "accessLevel": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "note": {
                    "$ref": "#/definitions/models.Note"
                },
                "noteID": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "models.NoteTag": {
            "type": "object",
            "properties": {
                "note": {
                    "$ref": "#/definitions/models.Note"
                },
                "noteID": {
                    "type": "string"
                },
                "tag": {
                    "$ref": "#/definitions/models.Tag"
                },
                "tagID": {
                    "type": "integer"
                }
            }
        },
        "models.Tag": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "noteTags": {
                    "description": "Relación: notas asociadas",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NoteTag"
                    }
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notePermissions": {
                    "description": "Relación: puede editar notas",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NotePermission"
                    }
                },
                "vaultPermissions": {
                    "description": "Relación: puede acceder a cajas",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.VaultPermission"
                    }
                },
                "vaults": {
                    "description": "Relación: owns (tiene cajas)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Vault"
                    }
                }
            }
        },
        "models.Vault": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "description": "Relación: contiene notas",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Note"
                    }
                },
                "owner": {
                    "$ref": "#/definitions/models.User"
                },
                "ownerID": {
                    "type": "string"
                },
                "permissions": {
                    "description": "Relación: permisos asignados",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.VaultPermission"
                    }
                }
            }
        },
        "models.VaultPermission": {
            "type": "object",
            "properties": {
                "accessLevel": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                },
                "userID": {
                    "type": "string"
                },
                "vault": {
                    "$ref": "#/definitions/models.Vault"
                },
                "vaultID": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Collab Notes API",
	Description:      "API para la aplicación de notas colaborativas.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
